import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Pradeep",
      email: "admin@example.com",
      password: bcrypt.hashSync("123", 8),
      isAdmin: true,
    },
    {
      name: "Timsina",
      email: "nonadmin@example.com",
      password: bcrypt.hashSync("123", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Umbro Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Umbro",
      rating: "4",
      numReviews: 11,
      description: "high quality product",
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 15,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Chinese Slim Shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 20,
      countInStock: 5,
      brand: "Chinese",
      rating: "4.5",
      numReviews: 10,
      description: "High Copy",
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 220,
      countInStock: 12,
      brand: 220,
      rating: "3.5",
      numReviews: 20,
      description: "high quality product",
    },
  ],
};

export default data;
