const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Umbro Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Umbro",
      brand: "Nike",
      rating: "4",
      numReviews: 11,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 0,
      brand: 120,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 15,
      brand: 120,
      brand: "Nike",
      rating: "4.5",
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Chinese Slim Shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 20,
      countInStock: 5,
      brand: 20,
      brand: "Chinese",
      rating: "4.5",
      numReviews: 10,
      description: "High Copy",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 220,
      countInStock: 12,
      brand: 220,
      brand: "Nike",
      rating: "3.5",
      numReviews: 20,
      description: "high quality product",
    },
  ],
};

export default data;
